title: jonnycake.tech
paginate: 5
paginate_path: "/page/:num/"

header_pages:
  - useful-links.md
  - about.md

minima:
  skin: dark
  date_format: "%Y-%m-%d"

  social_links:
    - icon: github
      url: "https://github.com/Jonnycake/"
      title: "Github Profile"
    - icon: linkedin
      url: "https://www.linkedin.com/in/jonnycake"
      title: "LinkedIn Account"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
