site_name: Jonnycake.Tech
title: Developer Portfolio & Blog
#gtag: G-YVTGX6JF66

socials:
  - name: Github Account
    label: github
    url: https://github.com/Jonnycake/
    icon: fa fa-github
  - name: LinkedIn account
    label: linkedin
    url: https://www.linkedin.com/in/jonnycake
    icon: fa fa-linkedin

collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - values:
      layout: default
  - scope:
      type: "projects"
    values:
      layout: project
  - scope:
      type: "posts"
    values:
      layout: post
